### ISSUE TITLE
developers.sparkapi.com appears to no longer exist

### ISSUE THREAD

**Issue by KristianL1415** [sparkapi/spark_api#134]
I am seeing references to https://developers.sparkapi.com and https://developers.sparkplatform.com in this project, however both of these endpoints appear to no longer be functioning. 

Currently I have a demo user, and while I can authenticate and get a token back for this user, I am unable to query for any data. Is there any way to get these developer endpoints working with demo accounts, or is there another way I should be going about this?

**Comment by codygustafson** [comment]
Sorry for the _late_ response @KristianL1415. There isn't a developer api which your demo key will work for. Your key will work on our production api when hitting https
://sparkapi.com/v1/endpoint which is the default configuration for this client.
