### ISSUE TITLE
POST as singular hash by default.

### ISSUE THREAD

**Issue by ifightcrime** [sparkapi/spark_api#42]
After talking with Josh. It sounds like the default standard is that all resources should support POST requests using a single Hash instead of an array.

This is just to remind me to look into that, since there's the potential of getting rid of all that pluralization logic crap.

He mentioned some of the older resources might not support that, but at least I can look into it and get a list or something. All new and future resources should support it though from what it sounds like.

**Comment by bhornseth** [comment]
Closing stale issue
