### ISSUE TITLE
Using Multiple User Accounts with spark gem

### ISSUE THREAD

**Issue by david-harkness** [sparkapi/spark_api#67]
We are developing an app using your gem (version 1.3.10).
The flow is that users will authenticate via oauth against the spart platform. Which yields us a user token.
However we're confused about how to allow many user accounts to work simultaneously.

 As far as I understand your gem does not allow to handle multiple concurrent requests using different user accounts. This is because of static implementation of connection (https://github.com/sparkapi/spark_api/blob/master/lib/spark_api.rb#L34) that is used from models (https://github.com/sparkapi/spark_api/blob/master/lib/spark_api/models/base.rb#L48)

Am I correct? If so do you have any suggestions or future plans to implement this?

**Comment by bhornseth** [comment]
Closing stale issue
