### ISSUE TITLE
OAuth refresh requires non nil code from provider

### ISSUE THREAD

**Issue by wlmcewen** [sparkapi/spark_api#7]
When working with a token that needs a refresh. The following error will arise unless I set the oauth2_provider.code attribute to a non nil value:

E, [2012-08-09T09:14:24.863684 #27221] ERROR -- : Authentication failed or server is sending us expired tokens, nothing we can do here.
/usr/local/rvm/gems/ree-1.8.7-2011.03/gems/spark_api-1.1.0/lib/spark_api/faraday_middleware.rb:49:in `on_complete': The token you provided is invalid.  A new authorization is required. (SparkApi::PermissionDenied)
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/faraday-0.8.1/lib/faraday/response.rb:9:in `call'
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/faraday-0.8.1/lib/faraday/response.rb:63:in `on_complete'
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/faraday-0.8.1/lib/faraday/response.rb:8:in `call'
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/faraday-0.8.1/lib/faraday/connection.rb:226:in `run_request'
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/faraday-0.8.1/lib/faraday/connection.rb:87:in `get'
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/spark_api-1.1.0/lib/spark_api/authentication/oauth2.rb:50:in `send'
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/spark_api-1.1.0/lib/spark_api/authentication/oauth2.rb:50:in `request'
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/spark_api-1.1.0/lib/spark_api/request.rb:72:in `request'
	from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/spark_api-1.1.0/lib/spark_api/request.rb:15:in `get'

**Comment by bhornseth** [comment]
@wlmcewen any idea if this is still an issue?

**Comment by wlmcewen** [comment]
I'm guessing not. Joshua redid a bunch of the Oauth flow a bit after this. Let's close it out, since it hasn't come up in over 3 years.
