### ISSUE TITLE
Error for searching MlsStatus like Closed, Expired and Cancelled

### ISSUE THREAD

**Issue by mechanicles** [sparkapi/spark_api#77]
This is my final query which becomes like, 

`{:_select=>"Id,ListingKey,ListPrice,BathsTotal,BedsTotal,LotSizeArea,StreetNumber,StreetDirPrefix,StreetName,StreetSuffix,StreetDirSuffix,StreetAdditionalInfo,City,PostalCode,YearBuilt,WaterFrontYN,DaysOnMarket,ListingId,ListingPrefix,PhotosCount,OnMarketDate,MlsStatus,BuildingAreaTotal,Latitude,Longitude,CustomFields", :_expand=>"PrimaryPhoto", :_limit=>10, :_pagination=>1, :_filter=>"(MlsStatus Eq 'Closed' OR MlsStatus Eq 'Expired') AND (PropertyType Eq 'A')", :_orderby=>"-ListPrice", :_page=>1}`

If I fire this query, I get this error 

`SparkApi::ClientError (The requested operation took too long to perform.  If running a search, try simplifying or adding additional restrictions to your _filter.  If ordering, try including the _orderby criteria in your _filter parameter.)`

I also added order_by and page criteria in the filter, still it gives me that error.

It works great on other status like Active, Active Contingent, Pending and Temp Off Market.

**Comment by bhornseth** [comment]
Closing stale issue
